### ISSUE TITLE
bug: panic in synchub while geminio dialogue_mgr close

### ISSUE THREAD

**Issue by singchia** [singchia/geminio#88]
```
>>> panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1292d39]

goroutine 38 [running]:
github.com/jumboframes/armorigo/synchub.(*SyncHub).Add(0x0, {0x1300780?, 0xc00033ce10}, {0xc00004d6e8, 0x1, 0xc00004d6b8?})
	github.com/jumboframes/armorigo@v0.4.0-rc.1/synchub/synchub.go:190 +0x179
github.com/jumboframes/armorigo/synchub.(*SyncHub).New(...)
	github.com/jumboframes/armorigo@v0.4.0-rc.1/synchub/synchub.go:175
github.com/singchia/geminio/multiplexer.(*dialogue).CloseWait.func1()
	github.com/singchia/geminio@v1.1.5-rc.1/multiplexer/dialogue.go:645 +0xc5
github.com/singchia/geminio/pkg/sync.(*Once).doSlow(0xc00004d768?, 0x1040f20?)
	github.com/singchia/geminio@v1.1.5-rc.1/pkg/sync/once.go:78 +0xbf
github.com/singchia/geminio/pkg/sync.(*Once).Do(...)
	github.com/singchia/geminio@v1.1.5-rc.1/pkg/sync/once.go:66
github.com/singchia/geminio/multiplexer.(*dialogue).CloseWait(0x12d7130?)
	github.com/singchia/geminio@v1.1.5-rc.1/multiplexer/dialogue.go:643 +0x3f
github.com/singchia/geminio/multiplexer.(*dialogueMgr).Close.func1(0xc0003b0000?)
	github.com/singchia/geminio@v1.1.5-rc.1/multiplexer/dialogue_mgr.go:428 +0x49
created by github.com/singchia/geminio/multiplexer.(*dialogueMgr).Close in goroutine 53
	github.com/singchia/geminio@v1.1.5-rc.1/multiplexer/dialogue_mgr.go:426 +0x1bb
```

**Comment by singchia** [comment]
the fini in dialogue_mgr may be called before DialogueOffline, then the dialogue in dialogues won't be found.
